# main menu navigation
menu:
  Home: /
  Archive: /archives
  Tag: /tags
  Maps: /maps
  # About: /about
  # EthFans: https://ethfans.org/
  Tools: /tools
  123BTC: https://123btc.org/

# home page default categories
home:
  categories: ['BTC', 'ORGIN-OF-MONEY', 'ETH' ]

# default logo image
logo:
  light: /images/light/logo.png
  dark: /images/dark/logo.png

widgets:
  - tag
  - archive
  - recent_posts
  - category

# social config
social:
  # github: btc-study/Bitcoin-ideas-Chinese-based-on-Nakamoto-Institute
  # rss:
  telegram: btcstudyorg
  # zhihu:
  # twitter: btcstudy
  # facebook: /
  # linkedin:
  # instagram: /
  nostr: npub1g2qs0ca5kpwlrcfug2em4jelmh65clk3yccwjxrs6hvdpd9qj80q022j4m

user:
  name: BTC study
  avatar: /images/avatar.png
  location: In the dust
  description: May the Force be with you

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: true
  repo: btc-study/Bitcoin-ideas-Chinese-based-on-Nakamoto-Institute # your blog repo

# dark
# light
# user-can-set
appearance: auto # Default value is auto

highlight:
  enable: true

# Miscellaneous
favicon: /favicon.ico

# MathJax Support
mathjax:
  enable: true
  cdn: https://cdn.jsdelivr.net/npm/mathjax@2.7.8/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# processon: https://www.processon.com/embed/61cac8cc1e08534776ea0505
